// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imancksprgqblbdrrfbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltYW5ja3NwcmdxYmxiZHJyZmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzI5NzEsImV4cCI6MjA2ODM0ODk3MX0.8GLzRnTKe1uty2UVdFeFFLqGPHbcRubgbEONC_40L8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});